spring.application.name=demo
server.port=8081 

spring.datasource.url=jdbc:postgresql://localhost:5432/Movie1
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aduy8774@gmail.com
spring.mail.password=xbko rmip yvlz ckrq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

google.client-id=1085883031350-7ihbulo2h3oure1c75sv8rc939b89rl4.apps.googleusercontent.com
google.client-secret=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
google.redirect-uri=http://localhost:3000/google-callback


jwt.signer-key=tndQadt/oKJtCAnWMh2eq74jx2xdwHEbfKcOfeJaDDPLDayULMjWeoNGOfH9rfQA

# [Config Pageable]
spring.data.web.pageable.one-indexed-parameters=true

# [Config OpenAI]
GOOGLE_API_KEY=AIzaSyAoGhES8Wk21K7UG5so81IAh6cBdUtkM8E
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Config VNPay
# VNPAY Configuration
vnpay.tmnCode=F7363RA1
vnpay.hashSecret=VL2ZFM15UPSSC2KGEU3X80VG7O23A3XV
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
# Backend return URL. Frontend will then redirect based on this.
vnpay.returnUrl=http://localhost:8081/api/bookings/payment/vnpay_return
# Frontend URL to redirect after successful/failed payment
frontend.payment.successUrl=http://localhost:3000/booking/success
frontend.payment.failureUrl=http://localhost:3000/booking/failure

