spring.application.name=demo
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.username=postgres

spring.datasource.password=12345


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aduy8774@gmail.com
spring.mail.password=xbko rmip yvlz ckrq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


jwt.signer-key=tndQadt/oKJtCAnWMh2eq74jx2xdwHEbfKcOfeJaDDPLDayULMjWeoNGOfH9rfQA

# [Config Pageable]
spring.data.web.pageable.one-indexed-parameters=true


spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

